/**
 * Auto-generated from seed/universe_symbols.csv — do not hand-edit.
 * Regenerate with: python3 -c "..." (see docs/universe-scan-improvements.md)
 * or re-run the snippet in the commit that introduced this file.
 */
export const DEFAULT_UNIVERSE_NAME = "All Symbols (954)";

export const DEFAULT_UNIVERSE_TICKERS: string[] = [
  "A", "AA", "AAPL", "AAPU", "ABBV", "ABNB", "ABSI", "ABT", "ACA", "ACGL",
  "ACN", "ADBE", "ADI", "ADM", "ADP", "ADSK", "AEE", "AEM", "AEP", "AES",
  "AFL", "AFRM", "AG", "AGG", "AGQ", "AI", "AIG", "AIZ", "AJG", "AKAM",
  "ALAB", "ALB", "ALGN", "ALGT", "ALK", "ALL", "ALLE", "ALLY", "ALNY", "ALV",
  "AMAT", "AMBA", "AMCR", "AMD", "AME", "AMGN", "AMKBY", "AMKR", "AMP", "AMPG",
  "AMT", "AMZN", "AMZU", "ANDE", "ANET", "ANFGF", "ANGPY", "AON", "AOS", "APA",
  "APD", "APH", "APLD", "APO", "APP", "APTV", "ARE", "ARES", "ARKG", "ARKK",
  "ARM", "ARQQ", "AS", "ASML", "ASX", "ATO", "ATOM", "ATRO", "AU", "AUR",
  "AVGO", "AVPT", "AVY", "AWK", "AXON", "AXP", "AZO", "B", "BA", "BABA",
  "BAC", "BALL", "BAX", "BBAI", "BBBY", "BBGI", "BBVA", "BBY", "BCHG", "BDX",
  "BEN", "BF-B", "BG", "BHP", "BIDU", "BIIB", "BILI", "BITB", "BITC", "BITO",
  "BITQ", "BITU", "BITX", "BKNG", "BKR", "BLDP", "BLDR", "BLK", "BMY", "BNY",
  "BOIL", "BOTZ", "BR", "BRK-B", "BRO", "BSOL", "BSX", "BSY", "BTC", "BTC-USD",
  "BTCT", "BTF", "BTU", "BUD", "BURL", "BX", "BXP", "BYDDF", "BYND", "BZFD",
  "C", "CAG", "CAH", "CAKE", "CARR", "CART", "CASY", "CAT", "CAVA", "CB",
  "CBOE", "CBRE", "CCEP", "CCI", "CCJ", "CCL", "CDNL", "CDNS", "CDW", "CEG",
  "CF", "CFG", "CG", "CHD", "CHKP", "CHRW", "CHTR", "CI", "CIEN", "CIFR",
  "CINF", "CL", "CLBT", "CLF", "CLNE", "CLSK", "CLX", "CMCSA", "CME", "CMG",
  "CMI", "CMS", "CNC", "CNP", "COF", "COHR", "COIN", "COLB", "CONL", "CONY",
  "COO", "COP", "COPX", "COR", "CORZ", "COST", "CPA", "CPAY", "CPNG", "CPRT",
  "CPT", "CRCL", "CRDO", "CRESY", "CRH", "CRL", "CRM", "CRML", "CRWD", "CRWV",
  "CSCO", "CSGP", "CSX", "CTAS", "CTSH", "CTVA", "CVNA", "CVS", "CVX", "CXAI",
  "D", "DAL", "DAR", "DASH", "DAX", "DD", "DDM", "DDOG", "DE", "DECK",
  "DELL", "DG", "DGX", "DHI", "DHR", "DIA", "DIS", "DLR", "DLTR", "DOC",
  "DOCN", "DOG", "DOGE-USD", "DOV", "DOW", "DPST", "DPZ", "DRI", "DRIP", "DRV",
  "DTE", "DUK", "DUST", "DVA", "DVN", "DXCM", "DXD", "EADSY", "EBAY", "ECHO",
  "ECL", "ED", "EDC", "EDZ", "EEM", "EEV", "EFX", "EG", "EIX", "EL",
  "ELM", "ELV", "EME", "EMR", "EOG", "EOSE", "EQIX", "EQT", "ERIE", "ERX",
  "ES", "ESS", "ESTC", "ET", "ETCG", "ETH", "ETH-USD", "ETHA", "ETHE", "ETHV",
  "ETHW", "ETN", "ETR", "ETSY", "EUM", "EVGOW", "EVR", "EVRG", "EW", "EWC",
  "EWG", "EWJ", "EWL", "EWU", "EWW", "EXC", "EXE", "EXPD", "EXPE", "EXR",
  "F", "FANG", "FAST", "FAZ", "FBIO", "FBL", "FCX", "FDS", "FDX", "FDXF",
  "FE", "FEMY", "FER", "FERG", "FETH", "FFIV", "FICO", "FIS", "FISV", "FITB",
  "FIX", "FKU", "FLEX", "FLMX", "FLNG", "FM", "FMS", "FORM", "FOX", "FOXA",
  "FRT", "FSLR", "FSLY", "FTAI", "FTNT", "FTV", "FUTU", "FVRR", "FXI", "GAP",
  "GBTC", "GD", "GDDY", "GDLC", "GE", "GEHC", "GEN", "GEV", "GFAI", "GFF",
  "GGLL", "GGLS", "GILD", "GIS", "GL", "GLD", "GLDM", "GLL", "GLNCY", "GLW",
  "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPCR", "GPN", "GRAB", "GRMN", "GRNY",
  "GRRR", "GS", "GTLB", "GUSH", "GWRE", "GWW", "GXO", "HACK", "HAIN", "HAL",
  "HAS", "HASI", "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HNGE", "HON",
  "HONA", "HOOD", "HOOG", "HOOX", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY",
  "HUBB", "HUBS", "HUM", "HUT", "HWM", "IBIT", "IBKR", "IBM", "ICE", "IDXX",
  "IEO", "IEV", "IEX", "IFF", "IGPT", "IHAK", "ILMN", "INCY", "INFQ", "INTC",
  "INTU", "INVH", "IONQ", "IOT", "IP", "IQ", "IQV", "IR", "IREN", "IRM",
  "ISRG", "IT", "ITUB", "ITW", "IVV", "IVZ", "IWM", "J", "JBHT", "JBL",
  "JCI", "JD", "JEF", "JKHY", "JKS", "JNJ", "JOBY", "JPM", "KDP", "KEY",
  "KEYS", "KHC", "KIM", "KKR", "KLAC", "KLIC", "KMB", "KMI", "KMX", "KNSL",
  "KO", "KOLD", "KR", "KRE", "KVUE", "KVYO", "KWEB", "L", "LABD", "LABU",
  "LAC", "LAES", "LB", "LCID", "LDOS", "LEN", "LH", "LHX", "LI", "LII",
  "LIN", "LITE", "LKNCY", "LLY", "LMND", "LMT", "LNT", "LOW", "LRCX", "LULU",
  "LUMN", "LUNR", "LUV", "LVS", "LWAY", "LYB", "LYFT", "LYG", "LYV", "MA",
  "MAA", "MAC", "MAR", "MARA", "MAS", "MBGYY", "MCD", "MCHP", "MCK", "MCO",
  "MDB", "MDLZ", "MDT", "MELI", "MET", "META", "MGM", "MGPI", "MHK", "MIDZ",
  "MKC", "MLM", "MMM", "MNST", "MO", "MOD", "MOS", "MP", "MPC", "MPWR",
  "MRK", "MRNA", "MRP", "MRSH", "MRVL", "MS", "MSCI", "MSFT", "MSFU", "MSI",
  "MSTR", "MSTU", "MT", "MTB", "MTD", "MU", "MUU", "MYY", "NBIS", "NCLH",
  "NDAQ", "NDSN", "NEE", "NEM", "NET", "NFLX", "NGVC", "NI", "NIO", "NKE",
  "NNN", "NOC", "NOK", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NTSK", "NU",
  "NUE", "NVD", "NVDA", "NVDL", "NVDX", "NVR", "NWS", "NWSA", "NXE", "NXPI",
  "O", "ODFL", "OGN", "OIH", "OKE", "OKLL", "OKLO", "OKTA", "OMC", "ON",
  "ONON", "ONTO", "ORCL", "ORLY", "OTF", "OTIS", "OUSM", "OWL", "OXY", "PAAS",
  "PANW", "PATH", "PAYX", "PBW", "PCAR", "PCG", "PDD", "PEG", "PEGA", "PEP",
  "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PKX", "PL", "PLD",
  "PLTR", "PM", "PNC", "PNFP", "PNR", "PNW", "PODD", "PONY", "PPG", "PPL",
  "PPLT", "PRSO", "PRU", "PSA", "PSKY", "PSQ", "PSX", "PTC", "PWR", "PYPL",
  "Q", "QBTS", "QBTX", "QBTZ", "QCOM", "QID", "QMCO", "QNC", "QQQ", "QS",
  "QSI", "QTUM", "QUBT", "QXO", "QYLD", "RBLX", "RCL", "RDDT", "RDW", "REBN",
  "REG", "REGN", "REMX", "RF", "RGTI", "RGTX", "RGTZ", "RIG", "RIO", "RIOT",
  "RIVN", "RJF", "RKDA", "RKLB", "RKLZ", "RL", "RLAY", "RMD", "ROBO", "ROK",
  "ROL", "ROOT", "ROP", "ROST", "RS", "RSG", "RSP", "RTX", "RUN", "RVTY",
  "RWM", "RXRX", "S", "SAIC", "SAN", "SAP", "SBAC", "SBB", "SBRA", "SBSW",
  "SBUX", "SCCO", "SCHW", "SCHW-PD", "SCO", "SDOW", "SDP", "SDS", "SEB", "SEMI",
  "SFM", "SFTBY", "SG", "SGML", "SH", "SHAK", "SHEL", "SHMD", "SHOP", "SHW",
  "SJM", "SKF", "SKHY", "SLB", "SLG", "SLV", "SMCI", "SMDD", "SMH", "SMST",
  "SMTC", "SN", "SNA", "SNDK", "SNDU", "SNOW", "SNPS", "SNX", "SO", "SOL-USD",
  "SOLT", "SOLV", "SOLZ", "SOUN", "SOUX", "SOXL", "SOXS", "SPAM", "SPCX", "SPG",
  "SPGI", "SPOT", "SPWR", "SPXL", "SPXS", "SPXU", "SQQQ", "SRE", "SRNE", "SRRK",
  "SRTA", "SRTY", "SRUUF", "SSG", "STE", "STLD", "STT", "STX", "STZ", "SW",
  "SWK", "SWKS", "SYF", "SYK", "SYM", "SYY", "SZK", "T", "TACK", "TAN",
  "TAP", "TBHC", "TCEHY", "TDC", "TDG", "TDOC", "TDY", "TEAM", "TECH", "TECK",
  "TECS", "TEL", "TER", "TEX", "TFC", "TGE", "TGT", "TH", "TIGR", "TJX",
  "TKO", "TLT", "TMO", "TMUS", "TNA", "TNK", "TOL", "TOST", "TPL", "TPR",
  "TQQQ", "TRGP", "TRI", "TRMB", "TRMD", "TROW", "TRV", "TSCO", "TSDD", "TSLA",
  "TSLL", "TSLR", "TSLS", "TSLZ", "TSM", "TSN", "TT", "TTD", "TTWO", "TUR",
  "TW", "TWLO", "TWM", "TXN", "TXT", "TYL", "TZA", "U", "UAL", "UBER",
  "UCAR", "UCO", "UCTT", "UCYB", "UDOW", "UDR", "UEC", "UGL", "UHS", "UI",
  "ULTA", "UNG", "UNH", "UNP", "UPRO", "UPS", "UPST", "UPWK", "URA", "URI",
  "URNM", "USB", "UVXY", "V", "VALE", "VECO", "VEEV", "VGK", "VGT", "VICI",
  "VIPS", "VIRT", "VIS", "VIXY", "VKTX", "VLO", "VLRS", "VLTO", "VMC", "VNOM",
  "VOX", "VRSK", "VRSN", "VRT", "VRTX", "VST", "VTR", "VTRS", "VTSAX", "VTWO",
  "VTWV", "VZ", "WAB", "WAL", "WANT", "WAT", "WBD", "WCBR", "WDAY", "WDC",
  "WEAT", "WEC", "WELL", "WEN", "WFC", "WHR", "WIMI", "WISE", "WIT", "WM",
  "WMB", "WMT", "WRB", "WSM", "WST", "WTI", "WTW", "WULF", "WY", "WYNN",
  "XEL", "XLB", "XLC", "XLE", "XLI", "XLU", "XMAG", "XOM", "XP", "XPEV",
  "XYL", "XYZ", "YANG", "YINN", "YMM", "YQ", "YUM", "ZBH", "ZBRA", "ZION",
  "ZM", "ZS", "ZSL", "ZTS",
];
