export function LandingFooter() {
  return (
    <footer data-testid="landing-footer" className="border-t border-white/5 pt-4 text-center text-xs text-gray-600 space-y-1">
      <p>
        Signals are generated by rules and an AI model from public market data (yfinance).
        Not financial advice.
      </p>
      <p>
        Methodology: see <code className="text-gray-500">docs/COMPLETE_FEATURES_GUIDE.md</code> in the repository.
      </p>
    </footer>
  );
}
